name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Configure sccache
      run: | 
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
          echo “SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.2
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.2
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
